# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from camerathread import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 911)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../media/root/Abhiraj WD/abhiraj/MRM/ai/Abhiraj/RoverGUI/Icons/logo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_4.addWidget(self.label_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.motorcode = QtWidgets.QPushButton(self.centralwidget)
        self.motorcode.setObjectName("motorcode")
        self.horizontalLayout_2.addWidget(self.motorcode)
        self.selectCameraCombo = QtWidgets.QComboBox(self.centralwidget)
        self.selectCameraCombo.setEditable(True)
        self.selectCameraCombo.setObjectName("selectCameraCombo")
        self.horizontalLayout_2.addWidget(self.selectCameraCombo)
        list = ["Webcam 0","Webcam 2","IP cam"]
        self.selectCameraCombo.addItems(list)
        self.selectCameraCombo.setCurrentIndex(-1)
        self.selectCameraCombo.setCurrentText("Choose from the following:")
        self.selectCameraCombo.setInsertPolicy(self.selectCameraCombo.InsertAtBottom)
        self.addCameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCameraButton.setObjectName("addCameraButton")
        self.horizontalLayout_2.addWidget(self.addCameraButton)
        self.closeCameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeCameraButton.setObjectName("closeCameraButton")
        self.horizontalLayout_2.addWidget(self.closeCameraButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gearLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.gearLabel.setFont(font)
        self.gearLabel.setObjectName("gearLabel")
        self.verticalLayout_2.addWidget(self.gearLabel, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        #spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headingLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(24)
        self.headingLabel.setFont(font)
        self.headingLabel.setObjectName("headingLabel")
        self.verticalLayout_3.addWidget(self.headingLabel, 0, QtCore.Qt.AlignHCenter)
        self.distLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        self.distLabel.setFont(font)
        self.distLabel.setObjectName("distLabel")
        self.verticalLayout_3.addWidget(self.distLabel, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        #spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_10.addItem(spacerItem4)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        #spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.th1 = Thread1(self)
        self.th2 = Thread2(self)
        self.th3 = Thread3(self)
        self.thm = ThreadM(self)
        self.thimu = ThreadIMU(self)

        self.selectCameraCombo.currentIndexChanged.connect(self.camopen)
        self.motorcode.clicked.connect(self.startmc)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camera Window"))
        self.motorcode.setText(_translate("MainWindow", "Motor Code"))
        self.addCameraButton.setText(_translate("MainWindow", "Add Camera"))
        self.closeCameraButton.setText(_translate("MainWindow", "Close Camera"))
        self.gearLabel.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "  Gear  "))
        self.label_6.setText(_translate("MainWindow", "OFF"))
        self.label.setText(_translate("MainWindow", "  Hill Assist  "))
        self.headingLabel.setText(_translate("MainWindow", "    "))
        self.distLabel.setText(_translate("MainWindow", "24 m"))
        self.label_9.setText(_translate("MainWindow", "X"))
        self.label_8.setText(_translate("MainWindow", "Y"))
        self.label_7.setText(_translate("MainWindow", "  Joystick values  "))
        self.label_14.setText(_translate("MainWindow", "Lat:"))
        self.label_15.setText(_translate("MainWindow", "Lon:"))

    def startmc(self):
        self.thm.start()
        self.thm.signalx.connect(self.label_11.setText)
        self.thm.signaly.connect(self.label_10.setText)
        self.thm.signalg.connect(self.gearLabel.setText)
        self.thm.signalh.connect(self.label_6.setText)
        self.thm.signala.connect(self.label_7.setText)
        self.thimu.start()
        self.thimu.signalIMU.connect(self.headingLabel.setText)

    def camopen(self,i):
        if i==-1:
            print("")
        elif i==0:
            self.addCameraButton.clicked.connect(self.cam1open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==1:
            self.addCameraButton.clicked.connect(self.cam2open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==2:
            self.addCameraButton.clicked.connect(self.cam3open)
            self.closeCameraButton.clicked.connect(self.camclose)

    def cam1open(self):
        self.th1.signal1.connect(self.label_1.setPixmap)
        self.th1.start()

    def cam2open(self):
        self.th2.signal2.connect(self.label_4.setPixmap)
        self.th2.start()

    def cam3open(self):
        self.th3.signal3.connect(self.label_3.setPixmap)
        self.th3.signal4.connect(self.label_5.setPixmap)
        self.th3.start()

    def camclose(self):
        self.th1.stop()
        self.th2.stop()
        self.th3.stop()
        os.execl(sys.executable, sys.executable, * sys.argv)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
