# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from cam import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(3000,2000)
        MainWindow.setStyleSheet('background : rgba(250,250,250,0.25)')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.motorcode = QtWidgets.QPushButton(self.centralwidget)
        self.motorcode.setObjectName("motorcode")
        self.horizontalLayout_2.addWidget(self.motorcode)
        self.selectCameraCombo = QtWidgets.QComboBox(self.centralwidget)
        self.selectCameraCombo.setEditable(True)
        self.selectCameraCombo.setObjectName("selectCameraCombo")
        self.horizontalLayout_2.addWidget(self.selectCameraCombo)
        list = ["IP cam mast","Cam 1","Cam 2","Cam 3","Cam 4","IP cam back","All"]
        self.selectCameraCombo.addItems(list)
        self.selectCameraCombo.setCurrentIndex(-1)
        self.selectCameraCombo.setCurrentText("Choose from the following:")
        self.selectCameraCombo.setInsertPolicy(self.selectCameraCombo.InsertAtBottom)
        self.addCameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCameraButton.setObjectName("addCameraButton")
        self.horizontalLayout_2.addWidget(self.addCameraButton)
        self.closeCameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeCameraButton.setObjectName("closeCameraButton")
        self.horizontalLayout_2.addWidget(self.closeCameraButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_17.addWidget(self.label_23)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headingLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(24)
        self.headingLabel.setFont(font)
        self.headingLabel.setObjectName("headingLabel")
        self.verticalLayout_3.addWidget(self.headingLabel, 0, QtCore.Qt.AlignHCenter)
        self.distLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        self.distLabel.setFont(font)
        self.distLabel.setObjectName("distLabel")
        self.verticalLayout_3.addWidget(self.distLabel, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setText("")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_13.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_15.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_4.addWidget(self.label_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.th1 = Thread1(self)
        self.th2 = Thread2(self)
        self.th3 = Thread3(self)
        self.th4 = Thread4(self)
        self.th5 = Thread5(self)
        self.th6 = Thread6(self)
        self.camfeed = CamFeed(self)
        self.thm = ThreadM(self)
        self.thud = ThreadHud(self)
        self.thgps = ThreadGPS(self)

        self.camfeed.start()
        self.selectCameraCombo.currentIndexChanged.connect(self.camopen)
        self.motorcode.clicked.connect(self.startmc)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Camera Window"))
        self.motorcode.setText(_translate("MainWindow", "Motor Code"))
        self.addCameraButton.setText(_translate("MainWindow", "Add Camera"))
        self.closeCameraButton.setText(_translate("MainWindow", "Close Camera"))
        self.label.setText(_translate("MainWindow", "GEAR"))
        self.label_2.setText(_translate("MainWindow", "Mast Cam"))
        self.label_6.setText(_translate("MainWindow", "Hill Assist"))
        self.label_16.setText(_translate("MainWindow", "OFF"))
        self.label_17.setText(_translate("MainWindow", "Link 1"))
        self.label_18.setText(_translate("MainWindow", "Link 2"))
        self.label_23.setText(_translate("MainWindow", "Gripper"))
        self.label_20.setText(_translate("MainWindow", "Swivel"))
        self.label_19.setText(_translate("MainWindow", "Arm values"))
        self.headingLabel.setText(_translate("MainWindow", "120°"))
        self.distLabel.setText(_translate("MainWindow", "24 m"))
        self.label_9.setText(_translate("MainWindow", "X"))
        self.label_8.setText(_translate("MainWindow", "Y"))
        self.label_14.setText(_translate("MainWindow", "Lat:"))
        self.label_15.setText(_translate("MainWindow", "Lon:"))
        self.label_24.setText(_translate("MainWindow", "Code"))

    def startmc(self):
        self.thm.start()
        self.thm.signalx.connect(self.label_11.setText)
        self.thm.signaly.connect(self.label_10.setText)
        self.thm.signalg.connect(self.label.setText)
        self.thm.signalh.connect(self.label_16.setText)
        self.thm.signalm.connect(self.label_2.setText)
        self.thm.signalL1.connect(self.label_17.setText)
        self.thm.signalL2.connect(self.label_18.setText)
        self.thm.signalc.connect(self.label_24.setText)
        self.thud.start()
        self.thud.signalHUD.connect(self.headingLabel.setPixmap)
        self.thgps.start()
        self.thgps.signalLat.connect(self.label_12.setText)
        self.thgps.signalLon.connect(self.label_13.setText)

    def camopen(self,i):
        if i==-1:
            print("")
        elif i==0:
            self.addCameraButton.clicked.connect(self.cam1open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==1:
            self.addCameraButton.clicked.connect(self.cam2open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==2:
            self.addCameraButton.clicked.connect(self.cam3open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==3:
            self.addCameraButton.clicked.connect(self.cam4open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==4:
            self.addCameraButton.clicked.connect(self.cam5open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==5:
            self.addCameraButton.clicked.connect(self.cam6open)
            self.closeCameraButton.clicked.connect(self.camclose)
        elif i==6:
            self.addCameraButton.clicked.connect(self.camopenAll)
            self.closeCameraButton.clicked.connect(self.camclose)
        else:
            print("")

    def cam1open(self):
        self.th1.signal1.connect(self.label_1.setPixmap)
        self.th1.start()

    def cam2open(self):
        self.th2.signal2.connect(self.label_7.setPixmap)
        self.th2.start()

    def cam3open(self):
        self.th3.signal3.connect(self.label_4.setPixmap)
        self.th3.start()

    def cam4open(self):
        self.th4.signal4.connect(self.label_3.setPixmap)
        self.th4.start()

    def cam5open(self):
        self.th5.signal5.connect(self.label_22.setPixmap)
        self.th5.start()

    def cam6open(self):
        self.th6.signal6.connect(self.label_5.setPixmap)
        self.th6.start()

    def camopenAll(self):
        self.th1.signal1.connect(self.label_1.setPixmap)
        self.th1.start()
        self.th2.signal2.connect(self.label_7.setPixmap)
        self.th2.start()
        self.th3.signal3.connect(self.label_4.setPixmap)
        self.th3.start()
        self.th4.signal4.connect(self.label_3.setPixmap)
        self.th4.start()
        self.th5.signal5.connect(self.label_22.setPixmap)
        self.th5.start()
        self.th6.signal6.connect(self.label_5.setPixmap)
        self.th6.start()

    def camclose(self):
        self.th1.stop()
        self.th2.stop()
        self.th3.stop()
        self.th4.stop()
        self.th5.stop()
        self.th6.stop()
        os.execl(sys.executable, sys.executable, * sys.argv)

try:
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
except KeyboardInterrupt:
    sys.exit()
    QCoreApplication.quit()
    QCoreApplication.exit(0)
